version: "3.2"
services:
  postgres:
    image: postgres:9.5.3
    container_name: postgres-9.5.3
    environment:
      - POSTGRES_PASSWORD=password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "5432:5432"
#  datanode:
#      # replace username/repo:tag with your name and image details
#      image: 52.0.211.45:5000/hadoop-base:03
#      deploy:
#        replicas: 2
#        restart_policy:
#          condition: on-failure
#        placement:
#          constraints:
#            - node.role == worker
#
